language: php

php:
  - '7.0'
  - '7.1'
  - '7.2'
  - '7.3'
  - nightly

#matrix:
#  # allow php nightly to fail
#  allow_failures:
#    - php: nightly

install: make install
script:
  - make test
  - if [[ $TRAVIS_PHP_VERSION = "7.2" ]]; then make check-style; fi
